import type { Client, Assessment, Treatment } from './supabase'

export const mockClients: Client[] = [
  {
    id: '1',
    pet_name: 'בוני',
    pet_breed: 'לברדור',
    pet_dob: '2018-03-15',
    pet_sex: 'זכר',
    pet_neutered: true,
    pet_weight: 32,
    owner_name: 'יעל כהן',
    owner_phone: '050-1234567',
    owner_email: 'yael@example.com',
    vet_name: 'ד"ר לוי',
    referrer: 'ד"ר לוי',
    insurance_company: 'כלל',
    created_at: '2024-01-10T10:00:00Z',
    is_active: true,
  },
  {
    id: '2',
    pet_name: 'לונה',
    pet_breed: 'גולדן רטריבר',
    pet_dob: '2020-07-22',
    pet_sex: 'נקבה',
    pet_neutered: true,
    pet_weight: 28,
    owner_name: 'דני ברק',
    owner_phone: '054-7654321',
    owner_email: 'dani@example.com',
    vet_name: 'ד"ר שפירו',
    referrer: 'המלצה',
    created_at: '2024-03-05T10:00:00Z',
    is_active: true,
  },
  {
    id: '3',
    pet_name: 'מקס',
    pet_breed: 'רועה גרמני',
    pet_dob: '2016-11-01',
    pet_sex: 'זכר',
    pet_neutered: false,
    pet_weight: 38,
    owner_name: 'שרה לוי',
    owner_phone: '052-9876543',
    created_at: '2023-08-20T10:00:00Z',
    is_active: true,
  },
]

export const mockAssessments: Assessment[] = [
  {
    id: 'a1',
    client_id: '1',
    date: '2024-01-10',
    reason: 'שמרני',
    chief_complaint: 'צליעה על הרגל האחורית הימנית',
    complaint_start: 'לפני 3 חודשים',
    affected_limb: 'אחורי ימני',
    complaint_progress: 'יציבה',
    gait_pattern: 'צליעה',
    pain_score: 3,
    bcs_score: 3,
    treatment_plan: 'סדרה של 8 טיפולי הידרו + פיזיו',
    series_count: 8,
    therapist_name: 'רוני',
  },
]

export const mockTreatments: Treatment[] = [
  {
    id: 't1',
    client_id: '1',
    date: '2024-01-15',
    treatment_number: 1,
    treatment_type: 'טיפול משולב פיזיו+הידרו',
    in_series: true,
    series_number: 1,
    series_total: 8,
    client_report: 'הכלב הרגיש טוב, שיתף פעולה',
    progress: 'תחילת טיפול',
    recommendations: 'להמשיך עם תרגילי בית יומיים',
    therapist_name: 'רוני',
  },
  {
    id: 't2',
    client_id: '1',
    date: '2024-01-22',
    treatment_number: 2,
    treatment_type: 'טיפול משולב פיזיו+הידרו',
    in_series: true,
    series_number: 2,
    series_total: 8,
    client_report: 'שיפור קל בצליעה',
    progress: 'שיפור',
    recommendations: 'להמשיך תרגילים, להוסיף Sit to stand',
    therapist_name: 'רוני',
  },
]
